// <auto-generated />
using System;
using GymTracer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracer.Migrations
{
    [DbContext(typeof(GymTracerDbContext))]
    [Migration("20260322125835_RemovedTrainingTicketsConnectionTable")]
    partial class RemovedTrainingTicketsConnectionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GymTracer.models.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            CreatedAt = new DateTime(2023, 1, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Code = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            CreatedAt = new DateTime(2023, 1, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Code = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            CreatedAt = new DateTime(2023, 1, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Code = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            CreatedAt = new DateTime(2023, 1, 23, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Code = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            CreatedAt = new DateTime(2023, 1, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Code = new Guid("f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c"),
                            CreatedAt = new DateTime(2023, 1, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Code = new Guid("a7b8c9d0-e1f2-3a4b-5c6d-7e8f9a0b1c2d"),
                            CreatedAt = new DateTime(2023, 1, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Code = new Guid("b8c9d0e1-f2a3-4b5c-6d7e-8f9a0b1c2d3e"),
                            CreatedAt = new DateTime(2023, 1, 27, 17, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            Code = new Guid("c9d0e1f2-a3b4-5c6d-7e8f-9a0b1c2d3e4f"),
                            CreatedAt = new DateTime(2023, 1, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            Code = new Guid("d0e1f2a3-b4c5-6d7e-8f9a-0b1c2d3e4f5a"),
                            CreatedAt = new DateTime(2023, 1, 29, 19, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 10L
                        });
                });

            modelBuilder.Entity("GymTracer.models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IssuerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<ulong>("TotalPrice")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("IssuerId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DueDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 1L,
                            PaymentDate = new DateTime(2023, 1, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00001",
                            TotalPrice = 5000ul
                        },
                        new
                        {
                            Id = 2L,
                            DueDate = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 2L,
                            PaymentDate = new DateTime(2023, 2, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00002",
                            TotalPrice = 45000ul
                        },
                        new
                        {
                            Id = 3L,
                            DueDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 3L,
                            PaymentDate = new DateTime(2023, 2, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00003",
                            TotalPrice = 20000ul
                        },
                        new
                        {
                            Id = 4L,
                            DueDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 4L,
                            PaymentDate = new DateTime(2023, 2, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00004",
                            TotalPrice = 3000ul
                        },
                        new
                        {
                            Id = 5L,
                            DueDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 5L,
                            PaymentDate = new DateTime(2023, 2, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00005",
                            TotalPrice = 40000ul
                        },
                        new
                        {
                            Id = 6L,
                            DueDate = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 6L,
                            PaymentDate = new DateTime(2023, 2, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00006",
                            TotalPrice = 2500ul
                        },
                        new
                        {
                            Id = 7L,
                            DueDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 7L,
                            PaymentDate = new DateTime(2023, 2, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00007",
                            TotalPrice = 22500ul
                        },
                        new
                        {
                            Id = 8L,
                            DueDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 8L,
                            ReceiptNumber = "REC-00008",
                            TotalPrice = 3500ul
                        },
                        new
                        {
                            Id = 9L,
                            DueDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 9L,
                            PaymentDate = new DateTime(2023, 3, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00009",
                            TotalPrice = 15000ul
                        },
                        new
                        {
                            Id = 10L,
                            DueDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuerId = 10L,
                            PaymentDate = new DateTime(2023, 3, 14, 19, 0, 0, 0, DateTimeKind.Utc),
                            ReceiptNumber = "REC-00010",
                            TotalPrice = 400000ul
                        });
                });

            modelBuilder.Entity("GymTracer.models.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStudent")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("MaxUsage")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Price")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Tax_key")
                        .HasColumnType("decimal(5, 2) unsigned");

                    b.Property<long?>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TrainingId");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("Tax_key_positive", "\"Tax_key\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Standard Daily Pass",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 5000ul,
                            Tax_key = 27.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Student Daily Pass",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 2500ul,
                            Tax_key = 27.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Monthly Full Pass",
                            IsActive = true,
                            IsStudent = false,
                            Price = 45000ul,
                            Tax_key = 27.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Student Monthly Pass",
                            IsActive = true,
                            IsStudent = true,
                            Price = 22500ul,
                            Tax_key = 27.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = 5L,
                            Description = "10-Occasion Pass",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 10ul,
                            Price = 40000ul,
                            Tax_key = 27.00m,
                            Type = 3
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Student 10-Occasion",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 10ul,
                            Price = 20000ul,
                            Tax_key = 27.00m,
                            Type = 3
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Standard Training Ticket - Yoga Basics",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 1L,
                            Type = 0
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Student Training Ticket - Yoga Basics",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 1L,
                            Type = 0
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Standard Training Ticket - HIIT Blast",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 2L,
                            Type = 0
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Student Training Ticket - HIIT Blast",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 2L,
                            Type = 0
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Standard Training Ticket - Pilates Core",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 3L,
                            Type = 0
                        },
                        new
                        {
                            Id = 12L,
                            Description = "Student Training Ticket - Pilates Core",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 3L,
                            Type = 0
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Standard Training Ticket - Zumba",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 4L,
                            Type = 0
                        },
                        new
                        {
                            Id = 14L,
                            Description = "Student Training Ticket - Zumba",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 4L,
                            Type = 0
                        },
                        new
                        {
                            Id = 15L,
                            Description = "Standard Training Ticket - CrossFit",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 5L,
                            Type = 0
                        },
                        new
                        {
                            Id = 16L,
                            Description = "Student Training Ticket - CrossFit",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 5L,
                            Type = 0
                        },
                        new
                        {
                            Id = 17L,
                            Description = "Standard Training Ticket - Spin Class",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 6L,
                            Type = 0
                        },
                        new
                        {
                            Id = 18L,
                            Description = "Student Training Ticket - Spin Class",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 6L,
                            Type = 0
                        },
                        new
                        {
                            Id = 19L,
                            Description = "Standard Training Ticket - Boxing",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 7L,
                            Type = 0
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Student Training Ticket - Boxing",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 7L,
                            Type = 0
                        },
                        new
                        {
                            Id = 21L,
                            Description = "Standard Training Ticket - Stretching",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 8L,
                            Type = 0
                        },
                        new
                        {
                            Id = 22L,
                            Description = "Student Training Ticket - Stretching",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 8L,
                            Type = 0
                        },
                        new
                        {
                            Id = 23L,
                            Description = "Standard Training Ticket - Powerlifting",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 9L,
                            Type = 0
                        },
                        new
                        {
                            Id = 24L,
                            Description = "Student Training Ticket - Powerlifting",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 9L,
                            Type = 0
                        },
                        new
                        {
                            Id = 25L,
                            Description = "Standard Training Ticket - Aqua Aerobics",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 6000ul,
                            Tax_key = 27.00m,
                            TrainingId = 10L,
                            Type = 0
                        },
                        new
                        {
                            Id = 26L,
                            Description = "Student Training Ticket - Aqua Aerobics",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 3000ul,
                            Tax_key = 27.00m,
                            TrainingId = 10L,
                            Type = 0
                        });
                });

            modelBuilder.Entity("GymTracer.models.Token", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenString")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_abc123def456",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 4, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_bcd234efg567",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 4, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_cde345fgh678",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 4, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_def456ghi789",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 4, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_efg567hij890",
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2023, 4, 6, 13, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_fgh678ijk901",
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2023, 4, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_ghi789jkl012",
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2023, 4, 8, 15, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_hij890klm123",
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2023, 4, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_ijk901lmn234",
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2023, 4, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TokenString = "token_jkl012mno345",
                            UserId = 10L
                        });
                });

            modelBuilder.Entity("GymTracer.models.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<ulong>("MaxParticipant")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EndTime")
                        .IsUnique();

                    b.HasIndex("StartTime")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Description = "Intro to Yoga",
                            EndTime = new DateTime(2023, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "yoga.jpg",
                            MaxParticipant = 20ul,
                            Name = "Yoga Basics",
                            StartTime = new DateTime(2023, 5, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Description = "High Intensity Interval Training",
                            EndTime = new DateTime(2023, 5, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Image = "hiit.jpg",
                            MaxParticipant = 15ul,
                            Name = "HIIT Blast",
                            StartTime = new DateTime(2023, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Description = "Core strengthening",
                            EndTime = new DateTime(2023, 5, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Image = "pilates.jpg",
                            MaxParticipant = 15ul,
                            Name = "Pilates Core",
                            StartTime = new DateTime(2023, 5, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Description = "Dance cardio",
                            EndTime = new DateTime(2023, 5, 2, 19, 0, 0, 0, DateTimeKind.Utc),
                            Image = "zumba.jpg",
                            MaxParticipant = 25ul,
                            Name = "Zumba Dance",
                            StartTime = new DateTime(2023, 5, 2, 18, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            Description = "Learn the basics of CrossFit",
                            EndTime = new DateTime(2023, 5, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            Image = "crossfit.jpg",
                            MaxParticipant = 10ul,
                            Name = "CrossFit Intro",
                            StartTime = new DateTime(2023, 5, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            Description = "Indoor cycling",
                            EndTime = new DateTime(2023, 5, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Image = "spin.jpg",
                            MaxParticipant = 20ul,
                            Name = "Spin Class",
                            StartTime = new DateTime(2023, 5, 4, 7, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            Description = "Pad work and technique",
                            EndTime = new DateTime(2023, 5, 5, 20, 0, 0, 0, DateTimeKind.Utc),
                            Image = "boxing.jpg",
                            MaxParticipant = 12ul,
                            Name = "Boxing Fundamentals",
                            StartTime = new DateTime(2023, 5, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            Description = "Recovery session",
                            EndTime = new DateTime(2023, 5, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Image = "stretch.jpg",
                            MaxParticipant = 20ul,
                            Name = "Stretching & Mobility",
                            StartTime = new DateTime(2023, 5, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            Description = "Squat, Bench, Deadlift",
                            EndTime = new DateTime(2023, 5, 7, 17, 30, 0, 0, DateTimeKind.Utc),
                            Image = "power.jpg",
                            MaxParticipant = 8ul,
                            Name = "Powerlifting 101",
                            StartTime = new DateTime(2023, 5, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            Description = "Pool workout",
                            EndTime = new DateTime(2023, 5, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Image = "aqua.jpg",
                            MaxParticipant = 15ul,
                            Name = "Aqua Aerobics",
                            StartTime = new DateTime(2023, 5, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = 6L
                        });
                });

            modelBuilder.Entity("GymTracer.models.TrainingUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OnWaitinglist")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Presence")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TrainingId", "UserId")
                        .IsUnique();

                    b.ToTable("TrainingUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationDate = new DateTime(2023, 4, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = true,
                            TrainingId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ApplicationDate = new DateTime(2023, 4, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = true,
                            TrainingId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ApplicationDate = new DateTime(2023, 4, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 3L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 4L,
                            ApplicationDate = new DateTime(2023, 4, 28, 13, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = true,
                            Presence = false,
                            TrainingId = 4L,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 5L,
                            ApplicationDate = new DateTime(2023, 4, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = true,
                            TrainingId = 5L,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 6L,
                            ApplicationDate = new DateTime(2023, 4, 30, 15, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = true,
                            TrainingId = 6L,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 7L,
                            ApplicationDate = new DateTime(2023, 5, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 7L,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 8L,
                            ApplicationDate = new DateTime(2023, 5, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = true,
                            TrainingId = 8L,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 9L,
                            ApplicationDate = new DateTime(2023, 5, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = true,
                            Presence = false,
                            TrainingId = 9L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ApplicationDate = new DateTime(2023, 5, 4, 19, 0, 0, 0, DateTimeKind.Utc),
                            OnWaitinglist = false,
                            Presence = true,
                            TrainingId = 10L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("GymTracer.models.UsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<int>("Gate")
                        .HasColumnType("int");

                    b.Property<DateTime>("UseDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("UsageLogs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CardId = 1L,
                            Gate = 1,
                            UseDate = new DateTime(2023, 5, 1, 7, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CardId = 2L,
                            Gate = 2,
                            UseDate = new DateTime(2023, 5, 1, 9, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            CardId = 3L,
                            Gate = 1,
                            UseDate = new DateTime(2023, 5, 2, 7, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            CardId = 4L,
                            Gate = 0,
                            UseDate = new DateTime(2023, 5, 2, 17, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            CardId = 5L,
                            Gate = 2,
                            UseDate = new DateTime(2023, 5, 3, 16, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            CardId = 6L,
                            Gate = 1,
                            UseDate = new DateTime(2023, 5, 4, 6, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            CardId = 7L,
                            Gate = 2,
                            UseDate = new DateTime(2023, 5, 5, 18, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            CardId = 8L,
                            Gate = 1,
                            UseDate = new DateTime(2023, 5, 6, 9, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            CardId = 9L,
                            Gate = 0,
                            UseDate = new DateTime(2023, 5, 7, 15, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10L,
                            CardId = 10L,
                            Gate = 2,
                            UseDate = new DateTime(2023, 5, 8, 8, 50, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GymTracer.models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            Name = "Alice Smith",
                            Password = "hashed_pw_1",
                            Role = 0
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            BirthDate = new DateTime(1985, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            Name = "Bob Jones",
                            Password = "hashed_pw_2",
                            Role = 0
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            BirthDate = new DateTime(1992, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 12, 10, 15, 0, 0, DateTimeKind.Utc),
                            Email = "charlie@example.com",
                            Name = "Charlie Brown",
                            Password = "hashed_pw_3",
                            Role = 1
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            BirthDate = new DateTime(1988, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 13, 11, 45, 0, 0, DateTimeKind.Utc),
                            Email = "diana@example.com",
                            Name = "Diana Prince",
                            Password = "hashed_pw_4",
                            Role = 0
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            BirthDate = new DateTime(1995, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 14, 14, 20, 0, 0, DateTimeKind.Utc),
                            Email = "evan@example.com",
                            Name = "Evan Wright",
                            Password = "hashed_pw_5",
                            Role = 0
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            BirthDate = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 15, 16, 5, 0, 0, DateTimeKind.Utc),
                            Email = "fiona@example.com",
                            Name = "Fiona Gallagher",
                            Password = "hashed_pw_6",
                            Role = 1
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            BirthDate = new DateTime(1980, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 16, 18, 50, 0, 0, DateTimeKind.Utc),
                            Email = "george@example.com",
                            Name = "George Miller",
                            Password = "hashed_pw_7",
                            Role = 0
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            BirthDate = new DateTime(1998, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 17, 7, 10, 0, 0, DateTimeKind.Utc),
                            Email = "hannah@example.com",
                            Name = "Hannah Abbott",
                            Password = "hashed_pw_8",
                            Role = 0
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            BirthDate = new DateTime(1975, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 18, 12, 35, 0, 0, DateTimeKind.Utc),
                            Email = "ian@example.com",
                            Name = "Ian Malcolm",
                            Password = "hashed_pw_9",
                            Role = 0
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            BirthDate = new DateTime(1999, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 19, 15, 25, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            Name = "Jane Doe",
                            Password = "hashed_pw_10",
                            Role = 0
                        },
                        new
                        {
                            Id = 11L,
                            Active = true,
                            BirthDate = new DateTime(1999, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 19, 15, 25, 0, 0, DateTimeKind.Utc),
                            Email = "tesztelek@example.com",
                            Name = "Teszt Elek",
                            Password = "hashed_pw_10",
                            Role = 2
                        },
                        new
                        {
                            Id = 12L,
                            Active = true,
                            BirthDate = new DateTime(1999, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreationDate = new DateTime(2023, 1, 19, 15, 25, 0, 0, DateTimeKind.Utc),
                            Email = "gitaron@example.com",
                            Name = "Git Áron",
                            Password = "hashed_pw_10",
                            Role = 3
                        });
                });

            modelBuilder.Entity("GymTracer.models.UserTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<ulong>("UsageAmount")
                        .HasColumnType("bigint unsigned");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTickets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2023, 1, 30, 10, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 1, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 1L,
                            TicketId = 1L,
                            UsageAmount = 1ul,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2023, 2, 4, 11, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 3, 4, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 2L,
                            TicketId = 3L,
                            UsageAmount = 0ul,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2023, 2, 9, 12, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 5, 9, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 3L,
                            TicketId = 6L,
                            UsageAmount = 5ul,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2023, 2, 14, 13, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 2, 15, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 4L,
                            TicketId = 7L,
                            UsageAmount = 1ul,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2023, 2, 19, 14, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 5, 19, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 5L,
                            TicketId = 5L,
                            UsageAmount = 2ul,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            CreationDate = new DateTime(2023, 2, 24, 15, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 2, 25, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 6L,
                            TicketId = 2L,
                            UsageAmount = 1ul,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            CreationDate = new DateTime(2023, 2, 28, 16, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 3, 28, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 7L,
                            TicketId = 4L,
                            UsageAmount = 0ul,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            CreationDate = new DateTime(2023, 3, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 3, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            PaymentId = 8L,
                            TicketId = 3L,
                            UsageAmount = 0ul,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            CreationDate = new DateTime(2023, 3, 9, 18, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2023, 4, 9, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 9L,
                            TicketId = 2L,
                            UsageAmount = 4ul,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            CreationDate = new DateTime(2023, 3, 14, 19, 5, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2024, 3, 14, 23, 59, 59, 0, DateTimeKind.Utc),
                            PaymentId = 10L,
                            TicketId = 8L,
                            UsageAmount = 0ul,
                            UserId = 10L
                        });
                });

            modelBuilder.Entity("GymTracer.models.Card", b =>
                {
                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.Payment", b =>
                {
                    b.HasOne("GymTracer.models.User", "Issuer")
                        .WithMany("Payments")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("GymTracer.models.Ticket", b =>
                {
                    b.HasOne("GymTracer.models.Training", "Training")
                        .WithMany("Tickets")
                        .HasForeignKey("TrainingId");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("GymTracer.models.Token", b =>
                {
                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.Training", b =>
                {
                    b.HasOne("GymTracer.models.User", "Trainer")
                        .WithMany("Training")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymTracer.models.TrainingUser", b =>
                {
                    b.HasOne("GymTracer.models.Training", "Training")
                        .WithMany("TrainingUsers")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("TrainingUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.UsageLog", b =>
                {
                    b.HasOne("GymTracer.models.Card", "Card")
                        .WithMany("UsageLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("GymTracer.models.UserTicket", b =>
                {
                    b.HasOne("GymTracer.models.Payment", "Payment")
                        .WithMany("UserTickets")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracer.models.Ticket", "Ticket")
                        .WithMany("UserTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("UserTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.Card", b =>
                {
                    b.Navigation("UsageLogs");
                });

            modelBuilder.Entity("GymTracer.models.Payment", b =>
                {
                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("GymTracer.models.Ticket", b =>
                {
                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("GymTracer.models.Training", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("TrainingUsers");
                });

            modelBuilder.Entity("GymTracer.models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Payments");

                    b.Navigation("Tokens");

                    b.Navigation("Training");

                    b.Navigation("TrainingUsers");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
