// <auto-generated />
using System;
using GymTracer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracer.Migrations
{
    [DbContext(typeof(GymTracerDbContext))]
    [Migration("20260414141521_newdatafix")]
    partial class newdatafix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GymTracer.models.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a001"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8L
                        },
                        new
                        {
                            Id = 2L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a002"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9L
                        },
                        new
                        {
                            Id = 3L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a003"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10L
                        },
                        new
                        {
                            Id = 4L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a004"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11L
                        },
                        new
                        {
                            Id = 5L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a005"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            UserId = 12L
                        },
                        new
                        {
                            Id = 7L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a007"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14L
                        },
                        new
                        {
                            Id = 8L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a008"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 35, 0, 0, DateTimeKind.Unspecified),
                            UserId = 15L
                        },
                        new
                        {
                            Id = 9L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a009"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            UserId = 16L
                        },
                        new
                        {
                            Id = 10L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a010"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 17L
                        },
                        new
                        {
                            Id = 11L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a011"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            UserId = 18L
                        },
                        new
                        {
                            Id = 12L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a012"),
                            CreatedAt = new DateTime(2026, 5, 1, 12, 55, 0, 0, DateTimeKind.Unspecified),
                            UserId = 19L
                        },
                        new
                        {
                            Id = 13L,
                            Code = new Guid("ae25016a-edd0-4e2a-85cf-5fb04f53a013"),
                            CreatedAt = new DateTime(2026, 5, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 20L
                        });
                });

            modelBuilder.Entity("GymTracer.models.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IssuerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<ulong>("TotalPrice")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("IssuerId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DueDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 8L,
                            PaymentDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-001",
                            TotalPrice = 2000ul
                        },
                        new
                        {
                            Id = 2L,
                            DueDate = new DateTime(2026, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 9L,
                            PaymentDate = new DateTime(2026, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-002",
                            TotalPrice = 18000ul
                        },
                        new
                        {
                            Id = 3L,
                            DueDate = new DateTime(2026, 5, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 10L,
                            PaymentDate = new DateTime(2026, 5, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-003",
                            TotalPrice = 2500ul
                        },
                        new
                        {
                            Id = 4L,
                            DueDate = new DateTime(2026, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 11L,
                            PaymentDate = new DateTime(2026, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-004",
                            TotalPrice = 22000ul
                        },
                        new
                        {
                            Id = 5L,
                            DueDate = new DateTime(2026, 5, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 12L,
                            PaymentDate = new DateTime(2026, 5, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-005",
                            TotalPrice = 1800ul
                        },
                        new
                        {
                            Id = 6L,
                            DueDate = new DateTime(2026, 5, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 13L,
                            PaymentDate = new DateTime(2026, 5, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-006",
                            TotalPrice = 18000ul
                        },
                        new
                        {
                            Id = 7L,
                            DueDate = new DateTime(2026, 5, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 14L,
                            PaymentDate = new DateTime(2026, 5, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-007",
                            TotalPrice = 2500ul
                        },
                        new
                        {
                            Id = 8L,
                            DueDate = new DateTime(2026, 5, 1, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 15L,
                            PaymentDate = new DateTime(2026, 5, 1, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-008",
                            TotalPrice = 22000ul
                        },
                        new
                        {
                            Id = 9L,
                            DueDate = new DateTime(2026, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 16L,
                            PaymentDate = new DateTime(2026, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-009",
                            TotalPrice = 2000ul
                        },
                        new
                        {
                            Id = 10L,
                            DueDate = new DateTime(2026, 5, 1, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 17L,
                            PaymentDate = new DateTime(2026, 5, 1, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-010",
                            TotalPrice = 1500ul
                        },
                        new
                        {
                            Id = 11L,
                            DueDate = new DateTime(2026, 5, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 18L,
                            PaymentDate = new DateTime(2026, 5, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-011",
                            TotalPrice = 18000ul
                        },
                        new
                        {
                            Id = 12L,
                            DueDate = new DateTime(2026, 5, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuerId = 19L,
                            PaymentDate = new DateTime(2026, 5, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiptNumber = "INV-202605-012",
                            TotalPrice = 2500ul
                        });
                });

            modelBuilder.Entity("GymTracer.models.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStudent")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("MaxUsage")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Price")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Tax_key")
                        .HasColumnType("decimal(5, 2) unsigned");

                    b.Property<long?>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TrainingId");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("Tax_key_positive", "\"Tax_key\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Napijegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2500ul,
                            Tax_key = 27.00m,
                            Type = 1
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Havi bérlet",
                            IsActive = true,
                            IsStudent = false,
                            Price = 18000ul,
                            Tax_key = 27.00m,
                            Type = 2
                        },
                        new
                        {
                            Id = 3L,
                            Description = "10 alkalmas bérlet",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 10ul,
                            Price = 22000ul,
                            Tax_key = 27.00m,
                            Type = 3
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Reggeli Jóga Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2000ul,
                            Tax_key = 27.00m,
                            TrainingId = 1L,
                            Type = 0
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Reggeli Jóga Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 1L,
                            Type = 0
                        },
                        new
                        {
                            Id = 6L,
                            Description = "CrossFit Kezdő Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2500ul,
                            Tax_key = 27.00m,
                            TrainingId = 2L,
                            Type = 0
                        },
                        new
                        {
                            Id = 7L,
                            Description = "CrossFit Kezdő Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 2L,
                            Type = 0
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Haladó TRX Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2200ul,
                            Tax_key = 27.00m,
                            TrainingId = 3L,
                            Type = 0
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Haladó TRX Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1600ul,
                            Tax_key = 27.00m,
                            TrainingId = 3L,
                            Type = 0
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Zumba Fit Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 4L,
                            Type = 0
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Zumba Fit Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1400ul,
                            Tax_key = 27.00m,
                            TrainingId = 4L,
                            Type = 0
                        },
                        new
                        {
                            Id = 12L,
                            Description = "Súlyemelés Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2500ul,
                            Tax_key = 27.00m,
                            TrainingId = 5L,
                            Type = 0
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Súlyemelés Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 5L,
                            Type = 0
                        },
                        new
                        {
                            Id = 14L,
                            Description = "Spinning 1 Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2000ul,
                            Tax_key = 27.00m,
                            TrainingId = 6L,
                            Type = 0
                        },
                        new
                        {
                            Id = 15L,
                            Description = "Spinning 1 Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 6L,
                            Type = 0
                        },
                        new
                        {
                            Id = 16L,
                            Description = "Pilates Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2000ul,
                            Tax_key = 27.00m,
                            TrainingId = 7L,
                            Type = 0
                        },
                        new
                        {
                            Id = 17L,
                            Description = "Pilates Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 7L,
                            Type = 0
                        },
                        new
                        {
                            Id = 18L,
                            Description = "Kettlebell Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2200ul,
                            Tax_key = 27.00m,
                            TrainingId = 8L,
                            Type = 0
                        },
                        new
                        {
                            Id = 19L,
                            Description = "Kettlebell Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1600ul,
                            Tax_key = 27.00m,
                            TrainingId = 8L,
                            Type = 0
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Box edzés Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2500ul,
                            Tax_key = 27.00m,
                            TrainingId = 9L,
                            Type = 0
                        },
                        new
                        {
                            Id = 21L,
                            Description = "Box edzés Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 9L,
                            Type = 0
                        },
                        new
                        {
                            Id = 22L,
                            Description = "HIIT Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2000ul,
                            Tax_key = 27.00m,
                            TrainingId = 10L,
                            Type = 0
                        },
                        new
                        {
                            Id = 23L,
                            Description = "HIIT Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 10L,
                            Type = 0
                        },
                        new
                        {
                            Id = 24L,
                            Description = "Core tréning Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 11L,
                            Type = 0
                        },
                        new
                        {
                            Id = 25L,
                            Description = "Core tréning Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1400ul,
                            Tax_key = 27.00m,
                            TrainingId = 11L,
                            Type = 0
                        },
                        new
                        {
                            Id = 26L,
                            Description = "Stretching Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 12L,
                            Type = 0
                        },
                        new
                        {
                            Id = 27L,
                            Description = "Stretching Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1000ul,
                            Tax_key = 27.00m,
                            TrainingId = 12L,
                            Type = 0
                        },
                        new
                        {
                            Id = 28L,
                            Description = "Funkcionális Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2200ul,
                            Tax_key = 27.00m,
                            TrainingId = 13L,
                            Type = 0
                        },
                        new
                        {
                            Id = 29L,
                            Description = "Funkcionális Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1600ul,
                            Tax_key = 27.00m,
                            TrainingId = 13L,
                            Type = 0
                        },
                        new
                        {
                            Id = 30L,
                            Description = "Aerobik Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 14L,
                            Type = 0
                        },
                        new
                        {
                            Id = 31L,
                            Description = "Aerobik Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1400ul,
                            Tax_key = 27.00m,
                            TrainingId = 14L,
                            Type = 0
                        },
                        new
                        {
                            Id = 32L,
                            Description = "Baba-mama Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2000ul,
                            Tax_key = 27.00m,
                            TrainingId = 15L,
                            Type = 0
                        },
                        new
                        {
                            Id = 33L,
                            Description = "Baba-mama Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 15L,
                            Type = 0
                        },
                        new
                        {
                            Id = 34L,
                            Description = "Gerinctorna Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 16L,
                            Type = 0
                        },
                        new
                        {
                            Id = 35L,
                            Description = "Gerinctorna Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1400ul,
                            Tax_key = 27.00m,
                            TrainingId = 16L,
                            Type = 0
                        },
                        new
                        {
                            Id = 36L,
                            Description = "Kardió mix Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2000ul,
                            Tax_key = 27.00m,
                            TrainingId = 17L,
                            Type = 0
                        },
                        new
                        {
                            Id = 37L,
                            Description = "Kardió mix Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1500ul,
                            Tax_key = 27.00m,
                            TrainingId = 17L,
                            Type = 0
                        },
                        new
                        {
                            Id = 38L,
                            Description = "Erőemelés Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2500ul,
                            Tax_key = 27.00m,
                            TrainingId = 18L,
                            Type = 0
                        },
                        new
                        {
                            Id = 39L,
                            Description = "Erőemelés Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1800ul,
                            Tax_key = 27.00m,
                            TrainingId = 18L,
                            Type = 0
                        },
                        new
                        {
                            Id = 40L,
                            Description = "Spinning 2 Jegy",
                            IsActive = true,
                            IsStudent = false,
                            MaxUsage = 1ul,
                            Price = 2200ul,
                            Tax_key = 27.00m,
                            TrainingId = 19L,
                            Type = 0
                        },
                        new
                        {
                            Id = 41L,
                            Description = "Spinning 2 Diák",
                            IsActive = true,
                            IsStudent = true,
                            MaxUsage = 1ul,
                            Price = 1600ul,
                            Tax_key = 27.00m,
                            TrainingId = 19L,
                            Type = 0
                        });
                });

            modelBuilder.Entity("GymTracer.models.Token", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenString")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 5, 1, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A360",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A361",
                            UserId = 8L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 5, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A362",
                            UserId = 9L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 5, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A363",
                            UserId = 10L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 5, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A364",
                            UserId = 11L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A365",
                            UserId = 12L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 5, 1, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A366",
                            UserId = 13L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 5, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A367",
                            UserId = 14L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 5, 1, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A368",
                            UserId = 15L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2026, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A369",
                            UserId = 16L
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2026, 5, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A370",
                            UserId = 17L
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2026, 5, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            RevokedAt = new DateTime(2026, 5, 2, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            TokenString = "575D6F6985153B428B4BEF8FD525BEA1F78E502B9DA6654A1EB774997C06B9F30FF132D9A44F296E176767A148175538579C459051474120FB85530D89C7A371",
                            UserId = 18L
                        });
                });

            modelBuilder.Entity("GymTracer.models.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<ulong>("MaxParticipant")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Description = "Frissítő napindító jóga",
                            EndTime = new DateTime(2026, 5, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "yoga_morning.jpg",
                            MaxParticipant = 15ul,
                            Name = "Reggeli Jóga",
                            StartTime = new DateTime(2026, 5, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Description = "Alapok elsajátítása",
                            EndTime = new DateTime(2026, 5, 6, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Image = "crossfit_basic.jpg",
                            MaxParticipant = 10ul,
                            Name = "CrossFit Kezdő",
                            StartTime = new DateTime(2026, 5, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 4L
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Description = "Saját testsúlyos edzés",
                            EndTime = new DateTime(2026, 5, 7, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "trx_pro.jpg",
                            MaxParticipant = 12ul,
                            Name = "Haladó TRX",
                            StartTime = new DateTime(2026, 5, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 5L
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Description = "Táncos kardió",
                            EndTime = new DateTime(2026, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "zumba.jpg",
                            MaxParticipant = 20ul,
                            Name = "Zumba Fit",
                            StartTime = new DateTime(2026, 5, 8, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            Description = "Erőfejlesztés",
                            EndTime = new DateTime(2026, 5, 10, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Image = "weightlifting.jpg",
                            MaxParticipant = 8ul,
                            Name = "Súlyemelés",
                            StartTime = new DateTime(2026, 5, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 7L
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            Description = "Kardió tekerés",
                            EndTime = new DateTime(2026, 5, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "spinning1.jpg",
                            MaxParticipant = 15ul,
                            Name = "Spinning 1",
                            StartTime = new DateTime(2026, 5, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            Description = "Core izmok erősítése",
                            EndTime = new DateTime(2026, 5, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "pilates.jpg",
                            MaxParticipant = 15ul,
                            Name = "Pilates",
                            StartTime = new DateTime(2026, 5, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            Description = "Dinamikus erőnléti",
                            EndTime = new DateTime(2026, 5, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Image = "kettlebell.jpg",
                            MaxParticipant = 12ul,
                            Name = "Kettlebell",
                            StartTime = new DateTime(2026, 5, 15, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 5L
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            Description = "Technika és állóképesség",
                            EndTime = new DateTime(2026, 5, 18, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Image = "box.jpg",
                            MaxParticipant = 10ul,
                            Name = "Box edzés",
                            StartTime = new DateTime(2026, 5, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            Description = "Magas intenzitású intervall",
                            EndTime = new DateTime(2026, 5, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "hiit.jpg",
                            MaxParticipant = 20ul,
                            Name = "HIIT",
                            StartTime = new DateTime(2026, 5, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 7L
                        },
                        new
                        {
                            Id = 11L,
                            Active = true,
                            Description = "Törzsizomzat fejlesztése",
                            EndTime = new DateTime(2026, 5, 22, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Image = "core.jpg",
                            MaxParticipant = 15ul,
                            Name = "Core tréning",
                            StartTime = new DateTime(2026, 5, 22, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            Active = true,
                            Description = "Nyújtás és lazítás",
                            EndTime = new DateTime(2026, 5, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "stretching.jpg",
                            MaxParticipant = 20ul,
                            Name = "Stretching",
                            StartTime = new DateTime(2026, 5, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 4L
                        },
                        new
                        {
                            Id = 13L,
                            Active = true,
                            Description = "Összetett gyakorlatok",
                            EndTime = new DateTime(2026, 5, 27, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "functional.jpg",
                            MaxParticipant = 12ul,
                            Name = "Funkcionális edzés",
                            StartTime = new DateTime(2026, 5, 27, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 5L
                        },
                        new
                        {
                            Id = 14L,
                            Active = true,
                            Description = "Klasszikus aerobik",
                            EndTime = new DateTime(2026, 5, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "aerobik.jpg",
                            MaxParticipant = 25ul,
                            Name = "Aerobik",
                            StartTime = new DateTime(2026, 5, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 6L
                        },
                        new
                        {
                            Id = 15L,
                            Active = true,
                            Description = "Szülés utáni regeneráció",
                            EndTime = new DateTime(2026, 6, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "babamama.jpg",
                            MaxParticipant = 10ul,
                            Name = "Baba-mama torna",
                            StartTime = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 7L
                        },
                        new
                        {
                            Id = 16L,
                            Active = true,
                            Description = "Tartásjavító torna",
                            EndTime = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "gerinc.jpg",
                            MaxParticipant = 15ul,
                            Name = "Gerinctorna",
                            StartTime = new DateTime(2026, 6, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 3L
                        },
                        new
                        {
                            Id = 17L,
                            Active = true,
                            Description = "Állóképesség fejlesztés",
                            EndTime = new DateTime(2026, 6, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "cardio.jpg",
                            MaxParticipant = 20ul,
                            Name = "Kardió mix",
                            StartTime = new DateTime(2026, 6, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 4L
                        },
                        new
                        {
                            Id = 18L,
                            Active = true,
                            Description = "Nehéz súlyok",
                            EndTime = new DateTime(2026, 6, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "powerlifting.jpg",
                            MaxParticipant = 8ul,
                            Name = "Erőemelés",
                            StartTime = new DateTime(2026, 6, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 5L
                        },
                        new
                        {
                            Id = 19L,
                            Active = true,
                            Description = "Haladó tekerés",
                            EndTime = new DateTime(2026, 6, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "spinning2.jpg",
                            MaxParticipant = 15ul,
                            Name = "Spinning 2",
                            StartTime = new DateTime(2026, 6, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 6L
                        });
                });

            modelBuilder.Entity("GymTracer.models.TrainingUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OnWaitinglist")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Presence")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TrainingId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TrainingId", "UserId")
                        .IsUnique();

                    b.ToTable("TrainingUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 1L,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 2L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 1L,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 3L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 2L,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 4L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 2L,
                            UserId = 11L
                        },
                        new
                        {
                            Id = 5L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 3L,
                            UserId = 12L
                        },
                        new
                        {
                            Id = 6L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 3L,
                            UserId = 13L
                        },
                        new
                        {
                            Id = 7L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 4L,
                            UserId = 14L
                        },
                        new
                        {
                            Id = 8L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 4L,
                            UserId = 15L
                        },
                        new
                        {
                            Id = 9L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 5L,
                            UserId = 16L
                        },
                        new
                        {
                            Id = 10L,
                            ApplicationDate = new DateTime(2026, 5, 1, 10, 55, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = true,
                            Presence = false,
                            TrainingId = 5L,
                            UserId = 17L
                        },
                        new
                        {
                            Id = 11L,
                            ApplicationDate = new DateTime(2026, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OnWaitinglist = false,
                            Presence = false,
                            TrainingId = 6L,
                            UserId = 18L
                        });
                });

            modelBuilder.Entity("GymTracer.models.UsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<int>("Gate")
                        .HasColumnType("int");

                    b.Property<DateTime>("UseDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("UsageLogs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CardId = 1L,
                            Gate = 1,
                            UseDate = new DateTime(2026, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CardId = 2L,
                            Gate = 1,
                            UseDate = new DateTime(2026, 5, 1, 14, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CardId = 3L,
                            Gate = 2,
                            UseDate = new DateTime(2026, 5, 1, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CardId = 4L,
                            Gate = 1,
                            UseDate = new DateTime(2026, 5, 1, 14, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CardId = 5L,
                            Gate = 2,
                            UseDate = new DateTime(2026, 5, 1, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6L,
                            CardId = 1L,
                            Gate = 3,
                            UseDate = new DateTime(2026, 5, 1, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7L,
                            CardId = 2L,
                            Gate = 3,
                            UseDate = new DateTime(2026, 5, 1, 15, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8L,
                            CardId = 3L,
                            Gate = 4,
                            UseDate = new DateTime(2026, 5, 1, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9L,
                            CardId = 6L,
                            Gate = 1,
                            UseDate = new DateTime(2026, 5, 1, 16, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10L,
                            CardId = 7L,
                            Gate = 2,
                            UseDate = new DateTime(2026, 5, 1, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11L,
                            CardId = 8L,
                            Gate = 1,
                            UseDate = new DateTime(2026, 5, 1, 16, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GymTracer.models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            BirthDate = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gym.hu",
                            Name = "Adminisztrátor Anna",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 3
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            BirthDate = new DateTime(1995, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ricsi.staff@gym.hu",
                            Name = "Recepciós Ricsi",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 2
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            BirthDate = new DateTime(1990, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elemer.edzo@gym.hu",
                            Name = "Edző Elemér",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 1
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            BirthDate = new DateTime(1992, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eszter.edzo@gym.hu",
                            Name = "Edző Eszter",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 1
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            BirthDate = new DateTime(1988, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erik.edzo@gym.hu",
                            Name = "Edző Erik",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 1
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            BirthDate = new DateTime(1994, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "edit.edzo@gym.hu",
                            Name = "Edző Edit",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 1
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            BirthDate = new DateTime(1991, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "endre.edzo@gym.hu",
                            Name = "Edző Endre",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 1
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            BirthDate = new DateTime(2001, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "janos.kovacs@gmail.com",
                            Name = "Kovács János",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            BirthDate = new DateTime(1998, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.nagy@gmail.com",
                            Name = "Nagy Anna",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            BirthDate = new DateTime(2003, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter.szabo@gmail.com",
                            Name = "Szabó Péter",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 11L,
                            Active = true,
                            BirthDate = new DateTime(1995, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.toth@gmail.com",
                            Name = "Tóth Mária",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 12L,
                            Active = true,
                            BirthDate = new DateTime(1990, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "laszlo.kiss@gmail.com",
                            Name = "Kiss László",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 13L,
                            Active = true,
                            BirthDate = new DateTime(1987, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.varga@gmail.com",
                            Name = "Varga Éva",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 14L,
                            Active = true,
                            BirthDate = new DateTime(1992, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 9, 55, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabor.molnar@gmail.com",
                            Name = "Molnár Gábor",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 15L,
                            Active = true,
                            BirthDate = new DateTime(1999, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "judit.farkas@gmail.com",
                            Name = "Farkas Judit",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 16L,
                            Active = true,
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "zoltan.balogh@gmail.com",
                            Name = "Balogh Zoltán",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 17L,
                            Active = true,
                            BirthDate = new DateTime(1985, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "andrea.papp@gmail.com",
                            Name = "Papp Andrea",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 18L,
                            Active = true,
                            BirthDate = new DateTime(1994, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "miklos.takacs@gmail.com",
                            Name = "Takács Miklós",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 19L,
                            Active = true,
                            BirthDate = new DateTime(1996, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            Email = "katalin.juhasz@gmail.com",
                            Name = "Juhász Katalin",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 20L,
                            Active = true,
                            BirthDate = new DateTime(1991, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "csaba.lakatos@gmail.com",
                            Name = "Lakatos Csaba",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 21L,
                            Active = true,
                            BirthDate = new DateTime(2002, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            Email = "krisztina.meszaros@gmail.com",
                            Name = "Mészáros Krisztina",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 22L,
                            Active = true,
                            BirthDate = new DateTime(1989, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "attila.simon@gmail.com",
                            Name = "Simon Attila",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 23L,
                            Active = true,
                            BirthDate = new DateTime(1997, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "agnes.fekete@gmail.com",
                            Name = "Fekete Ágnes",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 24L,
                            Active = true,
                            BirthDate = new DateTime(1986, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Email = "zsolt.toth@gmail.com",
                            Name = "Tóth Zsolt",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 25L,
                            Active = true,
                            BirthDate = new DateTime(1993, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 10, 55, 0, 0, DateTimeKind.Unspecified),
                            Email = "ildiko.szilagyi@gmail.com",
                            Name = "Szilágyi Ildikó",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 26L,
                            Active = true,
                            BirthDate = new DateTime(1998, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "balazs.torok@gmail.com",
                            Name = "Török Balázs",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 27L,
                            Active = true,
                            BirthDate = new DateTime(2004, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Email = "dora.feher@gmail.com",
                            Name = "Fehér Dóra",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 28L,
                            Active = true,
                            BirthDate = new DateTime(1995, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "tamas.racz@gmail.com",
                            Name = "Rácz Tamás",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 29L,
                            Active = true,
                            BirthDate = new DateTime(1992, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "viktoria.kis@gmail.com",
                            Name = "Kis Viktória",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        },
                        new
                        {
                            Id = 30L,
                            Active = true,
                            BirthDate = new DateTime(1990, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2026, 5, 1, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "gergo.gal@gmail.com",
                            Name = "Gál Gergő",
                            Password = "$pbkdf2$sha256$10$RzwqSi7MgrYQEcgSthPT7A==$db3Q+KxFdWEHFCemUKpLK7ygLIlIlChcJD+JJE0ltzXhNxobieAX2KjfnMVGJnyG",
                            Role = 0
                        });
                });

            modelBuilder.Entity("GymTracer.models.UserTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<ulong>("UsageAmount")
                        .HasColumnType("bigint unsigned");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTickets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2026, 5, 1, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 1L,
                            TicketId = 4L,
                            UsageAmount = 0ul,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2026, 5, 1, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 6, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 2L,
                            TicketId = 2L,
                            UsageAmount = 0ul,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2026, 5, 1, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 3L,
                            TicketId = 1L,
                            UsageAmount = 0ul,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2026, 5, 1, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 8, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 4L,
                            TicketId = 3L,
                            UsageAmount = 0ul,
                            UserId = 11L
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2026, 5, 1, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 6, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 5L,
                            TicketId = 7L,
                            UsageAmount = 0ul,
                            UserId = 12L
                        },
                        new
                        {
                            Id = 6L,
                            CreationDate = new DateTime(2026, 5, 1, 12, 35, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 6, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 6L,
                            TicketId = 2L,
                            UsageAmount = 0ul,
                            UserId = 13L
                        },
                        new
                        {
                            Id = 7L,
                            CreationDate = new DateTime(2026, 5, 1, 13, 5, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 10, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 7L,
                            TicketId = 12L,
                            UsageAmount = 0ul,
                            UserId = 14L
                        },
                        new
                        {
                            Id = 8L,
                            CreationDate = new DateTime(2026, 5, 1, 13, 35, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 8, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 8L,
                            TicketId = 3L,
                            UsageAmount = 0ul,
                            UserId = 15L
                        },
                        new
                        {
                            Id = 9L,
                            CreationDate = new DateTime(2026, 5, 1, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 9L,
                            TicketId = 14L,
                            UsageAmount = 0ul,
                            UserId = 16L
                        },
                        new
                        {
                            Id = 10L,
                            CreationDate = new DateTime(2026, 5, 1, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 10L,
                            TicketId = 17L,
                            UsageAmount = 0ul,
                            UserId = 17L
                        },
                        new
                        {
                            Id = 11L,
                            CreationDate = new DateTime(2026, 5, 1, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 6, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 11L,
                            TicketId = 2L,
                            UsageAmount = 0ul,
                            UserId = 18L
                        },
                        new
                        {
                            Id = 12L,
                            CreationDate = new DateTime(2026, 5, 1, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2026, 5, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            PaymentId = 12L,
                            TicketId = 1L,
                            UsageAmount = 0ul,
                            UserId = 19L
                        });
                });

            modelBuilder.Entity("GymTracer.models.Card", b =>
                {
                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.Payment", b =>
                {
                    b.HasOne("GymTracer.models.User", "Issuer")
                        .WithMany("Payments")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("GymTracer.models.Ticket", b =>
                {
                    b.HasOne("GymTracer.models.Training", "Training")
                        .WithMany("Tickets")
                        .HasForeignKey("TrainingId");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("GymTracer.models.Token", b =>
                {
                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.Training", b =>
                {
                    b.HasOne("GymTracer.models.User", "Trainer")
                        .WithMany("Training")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymTracer.models.TrainingUser", b =>
                {
                    b.HasOne("GymTracer.models.Training", "Training")
                        .WithMany("TrainingUsers")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("TrainingUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.UsageLog", b =>
                {
                    b.HasOne("GymTracer.models.Card", "Card")
                        .WithMany("UsageLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("GymTracer.models.UserTicket", b =>
                {
                    b.HasOne("GymTracer.models.Payment", "Payment")
                        .WithMany("UserTickets")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracer.models.Ticket", "Ticket")
                        .WithMany("UserTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTracer.models.User", "User")
                        .WithMany("UserTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracer.models.Card", b =>
                {
                    b.Navigation("UsageLogs");
                });

            modelBuilder.Entity("GymTracer.models.Payment", b =>
                {
                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("GymTracer.models.Ticket", b =>
                {
                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("GymTracer.models.Training", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("TrainingUsers");
                });

            modelBuilder.Entity("GymTracer.models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Payments");

                    b.Navigation("Tokens");

                    b.Navigation("Training");

                    b.Navigation("TrainingUsers");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
